name: oauth2-proxy
version: 3.2.6
apiVersion: v1
appVersion: 6.1.1
home: https://pusher.github.io/oauth2_proxy/
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
sources:
- https://github.com/pusher/oauth2_proxy
engine: gotpl
kubeVersion: ">=1.9.0-0"
maintainers:
  - name: ohdearaugustin
    url: https://github.com/ohdearaugustin
