---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "headscale.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "headscale.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headscale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["headscale"]
          args: ["serve"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          env:
            - name: SERVER_URL
              value: {{ .Values.headscale.server_url }}
            - name: LISTEN_ADDR
              value: {{ .Values.headscale.listen_addr }}
            - name: PRIVATE_KEY_PATH
              value: /vol/private-key/private-key
            - name: DERP_MAP_PATH
              value: /vol/config/derp.yaml
            - name: EPHEMERAL_NODE_INACTIVITY_TIMEOUT
              value: {{ .Values.headscale.ephemeral_node_inactivity_timeout }}
            - name: DB_TYPE
              value: sqlite3
            - name: DB_PATH
              value: /vol/data/db.sqlite
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: {{ include "headscale.fullname" . }}-data
              mountPath: /vol/data
            - name: private-key
              mountPath: /vol/private-key
            - name: derp
              mountPath: /vol/config/
      volumes:
      - name: private-key
        secret:
          secretName: {{ include "headscale.fullname" . }}-key
      - name: derp
        configMap:
          name: {{ include "headscale.fullname" .}}-derp
  volumeClaimTemplates:
  - metadata:
      name: {{ include "headscale.fullname" . }}-data
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
